// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0mCiBe0kgk1O2n_H0felODcZAJOfuH4',
    appId: '1:514341932122:web:6be777f1baffa512945c63',
    messagingSenderId: '514341932122',
    projectId: 'meetup-flutter-app',
    authDomain: 'meetup-flutter-app.firebaseapp.com',
    storageBucket: 'meetup-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvA1Pdc1O7YDDjDKAKnFgqX3rnm6-Wwc',
    appId: '1:514341932122:android:6fc5dc1946db080e945c63',
    messagingSenderId: '514341932122',
    projectId: 'meetup-flutter-app',
    storageBucket: 'meetup-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvy0i0T26Vrcrf9K0kP8oM-rmlbCf6keY',
    appId: '1:514341932122:ios:906c03fd7144d9bb945c63',
    messagingSenderId: '514341932122',
    projectId: 'meetup-flutter-app',
    storageBucket: 'meetup-flutter-app.appspot.com',
    iosClientId: '514341932122-2gtinev34v5rbj0ofui08emjkpjo0man.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMeetupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvy0i0T26Vrcrf9K0kP8oM-rmlbCf6keY',
    appId: '1:514341932122:ios:73a47b435319c5a5945c63',
    messagingSenderId: '514341932122',
    projectId: 'meetup-flutter-app',
    storageBucket: 'meetup-flutter-app.appspot.com',
    iosClientId: '514341932122-76vio61ib5peh955ohtpe2jvpi3p1dkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMeetupApp.RunnerTests',
  );
}
